### ISSUE TITLE
Consider using Postgres and implement it if suitable

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-remote#5]
Other FOSSASIA projects use Flask with Postgres. Please consider doing the same.

**Comment by jithinbp** [comment]
I was considering sqlite because no additional deployment tools are required, and only a single file on the disk does the job.
Also, since the PSLab hardware will only/should only be used by one user at a time, scalability is also not a big deal for the database.  
But I am also exploring postgres based on this [comparison](https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems)

**Comment by viveksb007** [comment]
@jithinbp Do we need to persist some data in between builds? sqlite is file based database and when any commit is made to repo a new build would start which would replace the db file previously made. And Heroku only supports Postgres db as a service.

**Comment by jithinbp** [comment]
If i use sqlite , I was thinking of putting it in the gitignore. The
databse is only used after deployment, and should be independent of the
backend.

Can heroku keep a persistent static file between builds? If so, users can
test builds based on the accounts created in the database as a one time
effort. Otherwise they'll have to create an account (takes five seconds) to
test each build. Or we can prepopulate the database with a few public
accounts (guest?)

It uses mysql for now, but I'm looking at possible alternatives.

On 23 Jul 2017 1:39 a.m., "Vivek Singh" <notifications@github.com> wrote:

@jithinbp <https://github.com/jithinbp> Do we need to persist some data in
between builds? sqlite is file based database and when any commit is made
to repo a new build would start which would replace the db file previously
made. And Heroku only supports Postgres db as a service.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/fossasia/pslab-remote/issues/5#issuecomment-317207500>,
or mute the thread

**Comment by niranjan94** [comment]
@jithinbp use something like [sqlalchemy](https://www.sqlalchemy.org/). This would allow us to use the DB engine we want depending on where we're running it. 

So, for heroku we can use postgres and maybe for local development/testing, SQLite can be used.

**Comment by mariobehling** [comment]
If you use a db library like sqlalchemy, with flask, you can use anything you want and freely switch between DBs without changing the code, depending on requirement.

**Comment by jithinbp** [comment]
@niranjan94 thanks. It appears to be quite flexible, and I'm experimenting with it.

**Comment by hongquan** [comment]
One thing you will suffer from SQLite is its very limited support of `ALTER TABLE`, which is to add/remove columns of a table, or change column's data type. This operation occurs when you change database structure.

The database migration has to use a trick with respect to SQLite: Create new table, copy data from old table to new data, delete old table.

**Comment by jithinbp** [comment]
@hongquan thanks, I went through these limitations. For now I've got postgres running fine on my local machine, and the same has also been set up on Heroku, so I'm not considering changing anything unnecessarily :)
